### ISSUE TITLE
doc build failure

### ISSUE THREAD

**Issue by samth** [ralsei/sawzall#4]
The documentation for the sawzall and graphite libraries has recently started failing.  See https://pkg-build.racket-lang.org/server/built/fail/sawzall.txt

Nothing changed in Racket that I think could have caused this, since that's just running 8.4. So it must be in a dependent package.

**Comment by samth** [comment]
The issue is a bug in the new version of `text-table`. Here's a small example in sawzall:

```
#lang racket
(require sawzall)


    (show (column-df [x (vector 1 2 3)]
                     [(string-append "a" "b") (vector "a" "b" "c")]))
```

**Comment by Metaxal** [comment]
Should be fixed by https://github.com/Metaxal/text-table/commit/cf3033e908fb63c519cc9f682b8b71c4b9647c7e
Sorry about that.

**Comment by ralsei** [comment]
Closing since it was an upstream issue.
Sorry for not seeing this! GitHub notifications... didn't tell me, inexplicably.
